services:
  couchdb:
    image: couchdb:3.5.0
    container_name: obsidian-couchdb
    restart: unless-stopped
    environment:
      - COUCHDB_USER=admin
    env_file:
      - ./secrets.couchdb.env
    volumes:
      - ./data:/opt/couchdb/data
      # IMPORTANT: CouchDB sometimes writes changes to this folder (e.g. password changes). So it
      #   needs to be writable.
      - ./files/couchdb/local.d:/opt/couchdb/etc/local.d
    mem_reservation: 450m # soft limit
    mem_limit: 512m # hard limit
    memswap_limit: 1g # hard limit including swap
    # This is required on some OSes (e.g. Debian Trixie) or else CouchDB will use about 2 GB of memory
    # without any databases. With this, the memory consumption is reduced to about 300 MB.
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  reverse-proxy:
    image: caddy:2.10.2-alpine
    container_name: obsidian-reverse-proxy
    restart: unless-stopped
    environment:
      - SERVER_HTTPS_PORT=${SERVER_HTTPS_PORT:-443}
    env_file:
      - ./secrets.proxy.env
    ports:
      - "${SERVER_HTTPS_PORT:-443}:${SERVER_HTTPS_PORT:-443}"
      - "80:80" # required for ACME HTTP01 challenge to get HTTPS certificates
    volumes:
      - ./files/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config/
      - caddy_data:/data/

volumes:
  # NOTE: Caddy requires these two volumes to persist across deployments.
  #   Primarily, the data volume which is used to store certificates Caddy
  #   got from Let's Encrypt. (Without this, Caddy would re-request its certificate
  #   over and over again and thus may run into a rate limit; see: https://letsencrypt.org/docs/rate-limits/.)
  #   See: https://hub.docker.com/_/caddy/#how-to-use-this-image
  caddy_config:
  caddy_data:
