services:
  couchdb:
    image: couchdb:3.5.0
    container_name: couchdb
    restart: unless-stopped
    environment:
      - COUCHDB_USER=admin
    env_file:
      - ./secrets.couchdb.env
    volumes:
      - ./data:/opt/couchdb/data
      # IMPORTANT: CouchDB sometimes writes changes to this folder (e.g. password changes). So it
      #   needs to be writable.
      - ./files/couchdb/local.d:/opt/couchdb/etc/local.d
    ports:
      - "127.0.0.1:5984:5984"
      #- "80:5984"
